/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.estacio.poo.alunos.frames;

import br.estacio.poo.alunos.dao.AlunoDAO;
import br.estacio.poo.alunos.dao.LoginDAO;
import br.estacio.poo.alunos.dao.TurmaAlunoDAO;
import br.estacio.poo.alunos.dao.TurmaDAO;
import br.estacio.poo.alunos.dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author fic
 */

public class FrameLogin extends javax.swing.JFrame {
private LoginDAO loginDAO = new LoginDAO();
private UsuarioDAO usuarioDAO = new UsuarioDAO();
private AlunoDAO alunoDAO = new AlunoDAO();
private TurmaDAO turmaDAO = new TurmaDAO();
private TurmaAlunoDAO turmaAlunoDAO = new TurmaAlunoDAO();
    /**
     * Creates new form FrameLogin
     */
     //FramePrincipal fp ;

        
    public FrameLogin() {
        
        initComponents();
        setLocationRelativeTo(null);
        lblMsg.setVisible(false);
        
        //Criando tabela de Usuarios
        //usuarioDAO.createTable();
        //Criando tabela de Alunos
        //alunoDAO.createTable();
        //Criando tabela de Turmas
        //turmaDAO.createTable();
        //Criando tabela de Turmas de Alunos
        //turmaAlunoDAO.createTable();
       
    }
     
    public void verificaSenha()
    {
        String login = tfUsuario.getText();
        String senha = pfSenha.getText();
        
        boolean resposta = loginDAO.verificarSenha(login, senha);
        if (resposta == true)
        {
            //loginDao.getUsuarioLogado();
            FramePrincipal.getInstancia().setUsuarioLogado(loginDAO.getUsuarioLogado());
            FramePrincipal.getInstancia().setVisible(true);
            dispose();
        }else {
            lblMsg.setVisible(true);
            pfSenha.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblRodape = new javax.swing.JLabel();
        btAcessar = new javax.swing.JButton();
        brSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login de Acesso");
        setBackground(new java.awt.Color(255, 255, 204));
        setName("Frame Login"); // NOI18N
        setUndecorated(true);

        lblTitulo.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N
        lblTitulo.setText("Cadastro de Alunos V2");

        lblUsuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblUsuario.setText("Usuário:");

        lblSenha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblSenha.setText("Senha:");

        lblRodape.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblRodape.setText("Desenvolvido por: David Alisson");

        btAcessar.setBackground(new java.awt.Color(204, 255, 204));
        btAcessar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/alunos/imagens/Botoes/acessar.png"))); // NOI18N
        btAcessar.setText("Acessar");
        btAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarActionPerformed(evt);
            }
        });

        brSair.setBackground(new java.awt.Color(153, 153, 255));
        brSair.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        brSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/alunos/imagens/Botoes/fechar.png"))); // NOI18N
        brSair.setText("Sair");
        brSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brSairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/alunos/imagens/Titulos/Login.png"))); // NOI18N

        lblMsg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setText("Login ou senha incorreto, por favor tente novamente !!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRodape)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblSenha)
                                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(217, 217, 217)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAcessar)
                        .addGap(8, 8, 8)
                        .addComponent(brSair, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brSair, btAcessar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSenha)
                        .addGap(7, 7, 7)
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRodape)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarActionPerformed
        verificaSenha();
    }//GEN-LAST:event_btAcessarActionPerformed

    private void brSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(FrameLogin.this, "Deseja realmente sair?","Verificação de Saída",
            JOptionPane.YES_OPTION); 
            if (opcao ==JOptionPane.YES_OPTION)
                System.exit(0);
        
    }//GEN-LAST:event_brSairActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brSair;
    private javax.swing.JButton btAcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblRodape;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

}
